pcall(require, 'impatient')

require('user_settings')
require('options')
require('autocmd')
require('mappings')
require('plugins')
require('config.colorscheme')
require('modules.key_listener')
require('modules.mode_nr')
require('modules.thincc')
