require('mellifluous').setup({
  dim_inactive = true,
  color_set = 'mellifluous',
  styles = {
    comments = 'italic',
    conditionals = 'NONE',
    folds = 'NONE',
    loops = 'NONE',
    functions = 'NONE',
    keywords = 'NONE',
    strings = 'NONE',
    variables = 'NONE',
    numbers = 'NONE',
    booleans = 'NONE',
    properties = 'NONE',
    types = 'NONE',
    operators = 'NONE',
  },
  transparent_background = {
    enabled = false,
    floating_windows = true,
    telescope = true,
    file_tree = true,
    cursor_line = true,
    status_line = false,
  },
  flat_background = {
    line_numbers = false,
    floating_windows = false,
    file_tree = false,
    cursor_line_number = false,
  },
  plugins = {
    cmp = true,
    gitsigns = true,
    indent_blankline = true,
    nvim_tree = {
      enabled = true,
      show_root = false,
    },
    telescope = {
      enabled = true,
      nvchad_like = true,
    },
    startify = true,
  },
})
