-- https://valentjn.github.io/ltex/settings.html

local ft = {
  'gitcommit',
  'markdown',
  'org',
  'pandoc',
  'text',
  'tex',
  'plaintex',
  'lua',
  'javascript',
  'typescript',
  'typescriptreact',
  'typescript',
  -- 'vue',
  'html',
  'toml',
  'yaml',
  'json',
  'rust',
  'go',
  'c',
  'cpp',
  'csharp',
  'dart',
  'fsharp',
  'groovy',
  'java',
  'kotlin',
  'php',
  'rust',
  'scala',
  'swift',
  'verilog',
  'elixir',
  'python',
  'coffeescript',
  'julia',
  'perl',
  'perl6',
  'puppet',
  'r',
  'ruby',
  'shellscript',
  'elm',
  'haskell',
  'sql',
  'clojure',
  'lisp',
  'matlab',
  'erlang',
  'fortran-modern',
  'vb',
}

return {
  filetypes = ft,
  settings = {
    ltex = {
      -- It's for checks comments in different languages
      -- https://github.com/valentjn/ltex-ls/blob/develop/src/main/kotlin/org/bsplines/ltexls/parsing/program/ProgramCommentRegexs.kt
      enabled = ft,
      checkFrequency = 'save',
      language = 'en-US',
      diagnosticSeverity = 'information',
      setenceCacheSize = 5000,
      additionalRules = {
        enablePickyRules = true,
      },
    },
  },
}
